name: "build"
description: "Build the project"
aliases: ["compile", "make"]

steps:
  - name: "Install dependencies"
    command: "{{.PackageManager}} install"
    condition: "file_exists package.json || file_exists requirements.txt"
  - name: "Run build script"
    command: "{{.BuildCommand}}"
  - name: "Verify build"
    command: "ls -la {{.BuildOutput}}"

env:
  NODE_ENV: "production"

metadata:
  category: "build"
  tags: ["compilation", "packaging"]